# Generated by Django 2.2.1 on 2019-06-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsive',
            name='overflow',
        ),
    ]
