# Generated by Django 2.2.1 on 2019-06-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0002_remove_responsive_overflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='menu',
            field=models.ManyToManyField(blank=True, to='svija.Menu'),
        ),
    ]
