# Generated by Django 2.2.1 on 2019-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0003_auto_20190618_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='svija.Menu'),
        ),
    ]
