# Generated by Django 2.2.1 on 2019-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0004_auto_20190618_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='menu',
            field=models.ManyToManyField(blank=True, to='svija.Menu'),
        ),
    ]
