# Generated by Django 2.2.1 on 2019-06-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0005_auto_20190618_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='svg',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
