# Generated by Django 2.2.1 on 2019-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0006_svg_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='maps_api_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Google Maps API key'),
        ),
    ]
