# Generated by Django 2.2.1 on 2019-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0007_auto_20190625_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear on next visit'),
        ),
        migrations.AddField(
            model_name='settings',
            name='cached',
            field=models.BooleanField(default=False, verbose_name='cached for admins'),
        ),
    ]
