# Generated by Django 2.2.1 on 2019-06-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0008_auto_20190625_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear cache for next visitor'),
        ),
    ]
