# Generated by Django 2.2.1 on 2019-06-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0009_auto_20190625_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['order'], 'verbose_name': 'svg file', 'verbose_name_plural': 'svg files'},
        ),
    ]
