# Generated by Django 2.2.3 on 2019-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0010_auto_20190625_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('sort1', models.CharField(blank=True, default='', max_length=100, verbose_name='main category')),
                ('sort2', models.CharField(blank=True, default='', max_length=100, verbose_name='sub category')),
                ('contents', models.TextField(blank=True, default='', max_length=20000, verbose_name='note')),
            ],
            options={
                'verbose_name': 'notes',
                'verbose_name_plural': 'notes',
            },
        ),
    ]
