# Generated by Django 2.2.3 on 2019-07-05 06:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0011_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='contents',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
