# Generated by Django 2.2.3 on 2019-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0012_auto_20190705_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
