# Generated by Django 2.2.3 on 2019-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0013_settings_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('sort1', models.CharField(blank=True, default='', max_length=100, verbose_name='main category')),
                ('sort2', models.CharField(blank=True, default='', max_length=100, verbose_name='sub category')),
                ('type', models.CharField(choices=[('head JS', 'head JS'), ('body JS', 'body JS'), ('HTML', 'HTML'), ('form', 'form'), ('mixed', 'mixed'), ('CSS', 'CSS')], default='', max_length=255, verbose_name='type')),
                ('content', models.TextField(default='', max_length=50000, verbose_name='content')),
            ],
            options={
                'ordering': ['type', 'name', 'sort1', 'sort2'],
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear cache'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cached',
            field=models.BooleanField(default=False, verbose_name='admins see cache'),
        ),
        migrations.AddField(
            model_name='page',
            name='library_script',
            field=models.ManyToManyField(blank=True, to='svija.LibraryScript'),
        ),
    ]
