# Generated by Django 2.2.3 on 2019-07-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0016_auto_20190707_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryscript',
            name='type',
            field=models.CharField(choices=[('head JS', 'head JS'), ('body JS', 'body JS'), ('HTML', 'HTML'), ('form', 'form'), ('CSS', 'CSS')], default='', max_length=255, verbose_name='type'),
        ),
    ]
