# Generated by Django 2.2.3 on 2019-11-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0017_auto_20190707_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name', 'active', 'sort1', 'sort2']},
        ),
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['order'], 'verbose_name': 'SVG file', 'verbose_name_plural': 'SVG files'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='responsive',
        ),
        migrations.AddField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sort1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='main category'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sort2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sub category'),
        ),
        migrations.AddField(
            model_name='page',
            name='override_modules',
            field=models.BooleanField(default=True, verbose_name='override modules (in responsive)'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='menu',
            field=models.ManyToManyField(blank=True, to='svija.Menu'),
        ),
        migrations.AddField(
            model_name='responsive',
            name='img_multiply',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=2, verbose_name='image resolution multiplier'),
        ),
        migrations.AddField(
            model_name='responsive',
            name='img_quality',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='JPG quality (0-100)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='backup_interval',
            field=models.CharField(choices=[('none', 'none'), ('6 hrs', '6 hrs'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly')], default='', max_length=255, verbose_name='backup interval'),
        ),
        migrations.AddField(
            model_name='settings',
            name='backup_next',
            field=models.BooleanField(default=False, verbose_name='backup on next visit'),
        ),
        migrations.AlterField(
            model_name='font',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='CSS reference'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='slug (follows prefix)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear cache on next visit'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cached',
            field=models.BooleanField(default=False, verbose_name='admins see cached content'),
        ),
    ]
