# Generated by Django 2.2.3 on 2019-11-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0018_auto_20191105_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('filename', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('sort1', models.CharField(blank=True, default='', max_length=100, verbose_name='main category')),
                ('sort2', models.CharField(blank=True, default='', max_length=100, verbose_name='sub category')),
            ],
            options={
                'ordering': ['name', 'active', 'sort1', 'sort2'],
            },
        ),
        migrations.CreateModel(
            name='PrefixModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='load order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Module')),
                ('Prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Prefix')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('head JS', 'head JS'), ('body JS', 'body JS'), ('CSS', 'CSS')], default='', max_length=255, verbose_name='type')),
                ('name', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='', max_length=50000, verbose_name='content')),
                ('order', models.IntegerField(default=0, verbose_name='load order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Module')),
            ],
            options={
                'verbose_name': 'extra script',
                'verbose_name_plural': 'extra scripts',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='prefix',
            name='module',
            field=models.ManyToManyField(through='svija.PrefixModules', to='svija.Module'),
        ),
    ]
