# Generated by Django 2.2.3 on 2019-11-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0019_auto_20191105_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefixmodules',
            old_name='Module',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='prefixmodules',
            old_name='Prefix',
            new_name='prefix',
        ),
    ]
