# Generated by Django 2.2.3 on 2019-11-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0020_auto_20191105_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='load order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Module')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Page')),
            ],
        ),
    ]
