# Generated by Django 2.2.3 on 2019-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0021_pagemodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='module',
            field=models.ManyToManyField(through='svija.PageModules', to='svija.Module'),
        ),
    ]
