# Generated by Django 2.2.3 on 2019-11-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0022_page_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='override_modules',
            new_name='suppress_modules',
        ),
    ]
