# Generated by Django 2.2.3 on 2019-11-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0023_auto_20191105_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='page',
            name='suppress_modules',
            field=models.BooleanField(default=True, verbose_name='suppress default modules (in Responsive)'),
        ),
    ]
