# Generated by Django 2.2.3 on 2019-11-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0024_auto_20191105_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Template'),
        ),
    ]
