# Generated by Django 2.2.3 on 2019-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0027_auto_20191105_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='suppress_modules',
            field=models.BooleanField(default=False, verbose_name='suppress default modules (in Responsive)'),
        ),
    ]
