# Generated by Django 2.2.3 on 2019-11-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0028_auto_20191105_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuscripts',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='page',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuScripts',
        ),
    ]
