# Generated by Django 2.2.3 on 2019-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0029_auto_20191107_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='override',
        ),
        migrations.AddField(
            model_name='page',
            name='override_dims',
            field=models.BooleanField(default=False, verbose_name='override dimensions'),
        ),
        migrations.AlterField(
            model_name='page',
            name='suppress_modules',
            field=models.BooleanField(default=False, verbose_name='suppress default modules'),
        ),
    ]
