# Generated by Django 2.2.3 on 2019-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0030_auto_20191107_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='default',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='responsive',
            name='img_multiply',
            field=models.DecimalField(decimal_places=1, default=2.4, max_digits=2, verbose_name='resolution multiple'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='backup_next',
            field=models.BooleanField(default=False, verbose_name='back up on next visit'),
        ),
    ]
