# Generated by Django 2.2.3 on 2019-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0031_auto_20191107_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Notes',
        ),
        migrations.AlterField(
            model_name='template',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
