# Generated by Django 2.2.3 on 2019-11-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0032_auto_20191107_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodules',
            options={'ordering': ['order'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='prefixmodules',
            options={'ordering': ['order'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
    ]
