# Generated by Django 2.2.3 on 2019-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0033_auto_20191108_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulescripts',
            options={'ordering': ['zindex'], 'verbose_name': 'extra script', 'verbose_name_plural': 'extra scripts'},
        ),
        migrations.AlterModelOptions(
            name='pagemodules',
            options={'ordering': ['zindex'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='prefixmodules',
            options={'ordering': ['zindex'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['zindex'], 'verbose_name': 'SVG file', 'verbose_name_plural': 'SVG files'},
        ),
        migrations.RemoveField(
            model_name='modulescripts',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pagemodules',
            name='order',
        ),
        migrations.RemoveField(
            model_name='prefixmodules',
            name='order',
        ),
        migrations.RemoveField(
            model_name='svg',
            name='order',
        ),
        migrations.AddField(
            model_name='modulescripts',
            name='zindex',
            field=models.IntegerField(default=0, verbose_name='z index'),
        ),
        migrations.AddField(
            model_name='pagemodules',
            name='zindex',
            field=models.IntegerField(default=0, verbose_name='load zindex'),
        ),
        migrations.AddField(
            model_name='prefixmodules',
            name='zindex',
            field=models.IntegerField(default=0, verbose_name='z index'),
        ),
        migrations.AddField(
            model_name='svg',
            name='zindex',
            field=models.IntegerField(default=0, verbose_name='z index'),
        ),
    ]
