# Generated by Django 2.2.3 on 2019-12-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0034_auto_20191108_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulescripts',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Module'),
        ),
        migrations.AlterField(
            model_name='page',
            name='prefix',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Prefix'),
        ),
        migrations.AlterField(
            model_name='page',
            name='shared',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Shared'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Template'),
        ),
        migrations.AlterField(
            model_name='pagemodules',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Module'),
        ),
        migrations.AlterField(
            model_name='pagemodules',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Page'),
        ),
        migrations.AlterField(
            model_name='pagescripts',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Page'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Language'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='responsive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Responsive'),
        ),
        migrations.AlterField(
            model_name='prefixmodules',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Module'),
        ),
        migrations.AlterField(
            model_name='prefixmodules',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Prefix'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='prefix',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Prefix', verbose_name='default prefix'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='robots',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Robots', verbose_name='robots.txt'),
        ),
        migrations.AlterField(
            model_name='shared',
            name='responsive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Responsive'),
        ),
        migrations.AlterField(
            model_name='sharedscripts',
            name='scripts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Shared'),
        ),
        migrations.AlterField(
            model_name='svg',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Page'),
        ),
    ]
