# Generated by Django 2.2.3 on 2019-12-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0035_auto_20191207_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='flag emoji'),
        ),
    ]
