# Generated by Django 2.2.3 on 2019-12-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0037_auto_20191207_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Redirect',
            new_name='Forwards',
        ),
    ]
