# Generated by Django 2.2.3 on 2019-12-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0038_auto_20191208_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='sort2',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='sort1',
            new_name='category',
        ),
    ]
