# Generated by Django 2.2.3 on 2019-12-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0040_auto_20191208_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'help article', 'verbose_name_plural': 'help articles'},
        ),
        migrations.AlterField(
            model_name='help',
            name='cat2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sub  category'),
        ),
        migrations.AlterField(
            model_name='help',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='link'),
        ),
    ]
