# Generated by Django 2.2.3 on 2019-12-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0041_auto_20191208_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='flag emoji'),
        ),
    ]
