# Generated by Django 2.2.3 on 2019-12-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0042_auto_20191208_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forwards',
            options={'verbose_name': 'forward', 'verbose_name_plural': 'forwards'},
        ),
    ]
