# Generated by Django 2.2.3 on 2019-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0043_auto_20191208_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulescripts',
            options={'ordering': ['order'], 'verbose_name': 'extra script', 'verbose_name_plural': 'extra scripts'},
        ),
        migrations.RemoveField(
            model_name='modulescripts',
            name='zindex',
        ),
        migrations.AddField(
            model_name='modulescripts',
            name='order',
            field=models.IntegerField(default=0, verbose_name='load order'),
        ),
        migrations.AlterField(
            model_name='pagemodules',
            name='zindex',
            field=models.IntegerField(default=0, verbose_name='z index'),
        ),
    ]
