# Generated by Django 2.2.3 on 2019-12-14 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0044_auto_20191211_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svg',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Page'),
        ),
    ]
