# Generated by Django 2.2.3 on 2019-12-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0045_auto_20191214_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodules',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Page'),
        ),
        migrations.AlterField(
            model_name='pagescripts',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Page'),
        ),
    ]
