# Generated by Django 2.2.3 on 2020-02-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0046_auto_20191214_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear cache on next visit'),
        ),
        migrations.AddField(
            model_name='page',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear cache on next visit'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear cache on next visit DEPRECATED'),
        ),
    ]
