# Generated by Django 2.2.3 on 2020-02-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0047_auto_20200214_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulescripts',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Module'),
        ),
    ]
