# Generated by Django 2.2.3 on 2020-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0048_auto_20200214_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shared',
            options={'verbose_name': 'Sitewide Scripts', 'verbose_name_plural': 'Sitewide Scripts'},
        ),
        migrations.AlterModelOptions(
            name='sharedscripts',
            options={'ordering': ['order'], 'verbose_name': 'included script', 'verbose_name_plural': 'included scripts'},
        ),
        migrations.AlterField(
            model_name='font',
            name='active',
            field=models.BooleanField(default=True, verbose_name='include in CSS'),
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SVG file (optional)'),
        ),
    ]
