# Generated by Django 2.2.3 on 2020-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0049_auto_20200313_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='access_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='readability link name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='access_text',
            field=models.TextField(blank=True, default='', max_length=50000, verbose_name='readabiliy content'),
        ),
    ]
