# Generated by Django 2.2.3 on 2020-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0050_auto_20200318_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='active',
            field=models.BooleanField(default=True, verbose_name='include in page'),
        ),
        migrations.AlterField(
            model_name='font',
            name='source',
            field=models.CharField(blank=True, default='SOURCE NEEDED', max_length=100, verbose_name='source'),
        ),
    ]
