# Generated by Django 2.2.3 on 2020-03-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0051_auto_20200318_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodules',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.Module'),
        ),
    ]
