# Generated by Django 2.2.3 on 2020-04-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0052_auto_20200318_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='active',
            field=models.BooleanField(default=True, verbose_name='include'),
        ),
        migrations.AlterField(
            model_name='page',
            name='access_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='page name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='access_text',
            field=models.TextField(blank=True, default='', max_length=50000, verbose_name='snippet content'),
        ),
        migrations.AlterField(
            model_name='template',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default (not implemented)'),
        ),
        migrations.AlterField(
            model_name='template',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='filename'),
        ),
    ]
