# Generated by Django 2.2.3 on 2020-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0053_auto_20200417_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='access_name',
            new_name='snippet_name',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='access_text',
            new_name='snippet_text',
        ),
        migrations.AlterField(
            model_name='language',
            name='comment',
            field=models.TextField(default='Site built entirely in SVG with Svija – visit svija.com for more information!', max_length=5000, verbose_name='source code message'),
        ),
        migrations.AlterField(
            model_name='language',
            name='default',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='sender if email fails verifcation'),
        ),
        migrations.AlterField(
            model_name='language',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='destination address'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_alert_fail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='message failed alert'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_alert_rcvd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='message sent alert'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='email label'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name label'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_rcvd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='message after sent'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_send',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='send button label'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_sending',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='message while sending'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='default message value'),
        ),
        migrations.AlterField(
            model_name='language',
            name='mail_frm',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='sending address in email body'),
        ),
        migrations.AlterField(
            model_name='language',
            name='no_email',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='sender if only phone number is given'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='second part of page title'),
        ),
        migrations.AlterField(
            model_name='language',
            name='touch',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='iPhone icon name'),
        ),
    ]
