# Generated by Django 2.2.3 on 2020-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0054_auto_20200417_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='name',
            new_name='css',
        ),
        migrations.AlterField(
            model_name='template',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='template',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='subfolder & filename'),
        ),
    ]
