# Generated by Django 2.2.3 on 2020-04-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0055_auto_20200421_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='template',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='JPG quality (0-100)'),
        ),
    ]
