# Generated by Django 2.2.3 on 2020-04-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0056_auto_20200421_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='default',
        ),
    ]
