# Generated by Django 2.2.3 on 2020-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0057_remove_template_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='language',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='template',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='template',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='filename'),
        ),
    ]
