# Generated by Django 2.2.3 on 2020-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0058_auto_20200421_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['display_order', 'name', 'active', 'sort1', 'sort2']},
        ),
        migrations.AddField(
            model_name='module',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='display order'),
        ),
    ]
