# Generated by Django 2.2.3 on 2020-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0059_auto_20200421_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsive',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Responsive'},
        ),
        migrations.AddField(
            model_name='responsive',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='display order'),
        ),
    ]
