# Generated by Django 2.2.3 on 2020-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0060_auto_20200421_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefix',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Prefixes'},
        ),
        migrations.AddField(
            model_name='prefix',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='display order'),
        ),
    ]
