# Generated by Django 2.2.3 on 2020-04-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0062_auto_20200421_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['display_order', 'prefix', 'url', '-pub_date']},
        ),
    ]
