# Generated by Django 2.2.3 on 2020-04-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0063_auto_20200421_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'verbose_name': 'Font', 'verbose_name_plural': '3.1 · Fonts'},
        ),
        migrations.AlterModelOptions(
            name='forwards',
            options={'verbose_name': 'Redirects', 'verbose_name_plural': '4.2 · Redirects'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'help article', 'verbose_name_plural': '4.5 · Help'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['display_order'], 'verbose_name_plural': '1.2 · Languages'},
        ),
        migrations.AlterModelOptions(
            name='libraryscript',
            options={'ordering': ['type', 'name', 'sort1', 'sort2'], 'verbose_name': 'Optional Scripts', 'verbose_name_plural': '3.3 · Optional Scripts'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['display_order', 'name', 'active', 'sort1', 'sort2'], 'verbose_name_plural': '2.2 · Modules'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': '4.4 · My Notes'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['display_order', 'prefix', 'url', '-pub_date'], 'verbose_name_plural': '2.1 · Pages'},
        ),
        migrations.AlterModelOptions(
            name='prefix',
            options={'ordering': ['display_order'], 'verbose_name_plural': '1.4 · Prefix Codes'},
        ),
        migrations.AlterModelOptions(
            name='responsive',
            options={'ordering': ['display_order'], 'verbose_name_plural': '1.3 · Responsive Options'},
        ),
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name': 'Robots.txt', 'verbose_name_plural': '4.1· Robots.txt'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': '1.1 · Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='shared',
            options={'verbose_name': 'Sitewide Scripts', 'verbose_name_plural': '3.2 · Sitewide Scripts'},
        ),
        migrations.AlterModelOptions(
            name='sharedscripts',
            options={'ordering': ['order'], 'verbose_name': 'included script'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['display_order'], 'verbose_name_plural': '4.3 · Templates'},
        ),
    ]
