# Generated by Django 2.2.3 on 2020-04-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0064_auto_20200421_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['active', 'display_order', 'name', 'sort1', 'sort2'], 'verbose_name_plural': '2.2 · Modules'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['visitable', 'display_order', 'prefix', 'url', '-pub_date'], 'verbose_name_plural': '2.1 · Pages'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['active', 'display_order'], 'verbose_name_plural': '4.3 · Templates'},
        ),
    ]
