# Generated by Django 2.2.3 on 2020-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0065_auto_20200421_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mod_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
