# Generated by Django 2.2.3 on 2020-04-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0066_page_mod_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['visitable', 'display_order', 'prefix', 'url', '-mod_date'], 'verbose_name_plural': '2.1 · Pages'},
        ),
    ]
