# Generated by Django 2.2.3 on 2020-04-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0068_auto_20200421_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='tracking_on',
            field=models.BooleanField(default=False, verbose_name='allow cookies unless opted out'),
        ),
    ]
