# Generated by Django 2.2.3 on 2020-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0069_settings_tracking_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['visitable', 'display_order', '-prefix', 'url', '-pub_date'], 'verbose_name_plural': '2.1 · Pages'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='active',
            field=models.BooleanField(default=False, verbose_name='site is online'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tracking_on',
            field=models.BooleanField(default=False, verbose_name='cookies allowed by default'),
        ),
    ]
