# Generated by Django 2.2.3 on 2020-04-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0070_auto_20200424_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-visitable', 'display_order', 'prefix', 'url', '-pub_date'], 'verbose_name_plural': '2.1 · Pages'},
        ),
    ]
