# Generated by Django 3.0.7 on 2020-06-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0072_auto_20200617_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='p3_color',
            field=models.BooleanField(default=True, verbose_name='display P3 color space where possible'),
        ),
    ]
