# Generated by Django 3.0.7 on 2020-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0075_auto_20200617_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwards',
            name='to_prefix',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='to prefix, http or https'),
        ),
    ]
