# Generated by Django 3.0.7 on 2020-06-18 06:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0076_auto_20200617_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwards',
            name='from_url',
            field=models.CharField(default='', max_length=200, verbose_name='old URL'),
        ),
        migrations.AlterField(
            model_name='forwards',
            name='to_page',
            field=models.CharField(default='', max_length=200, verbose_name='new URL'),
        ),
        migrations.AlterField(
            model_name='forwards',
            name='to_prefix',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='prefix, HTTP or HTTPS'),
        ),
        migrations.AlterField(
            model_name='page',
            name='snippet_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
