# Generated by Django 3.0.7 on 2020-06-18 07:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0077_auto_20200618_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwards',
            name='to_prefix',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='new prefix, HTTP or HTTPS'),
        ),
        migrations.AlterField(
            model_name='page',
            name='snippet_text',
            field=ckeditor.fields.RichTextField(verbose_name='accessibility content'),
        ),
    ]
