# Generated by Django 3.0.7 on 2020-06-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0078_auto_20200618_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryscript',
            name='type',
            field=models.CharField(choices=[('head JS', 'head JS'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('form', 'form'), ('body JS', 'body JS')], default='', max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='modulescripts',
            name='type',
            field=models.CharField(choices=[('head JS', 'head JS'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('form', 'form'), ('body JS', 'body JS')], default='', max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='pagescripts',
            name='type',
            field=models.CharField(choices=[('head JS', 'head JS'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('form', 'form'), ('body JS', 'body JS')], default='', max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='sharedscripts',
            name='type',
            field=models.CharField(choices=[('head JS', 'head JS'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('form', 'form'), ('body JS', 'body JS')], default='', max_length=255, verbose_name='type'),
        ),
    ]
