# Generated by Django 3.0.7 on 2020-06-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0079_auto_20200622_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-active', 'display_order', 'name', 'sort1', 'sort2'], 'verbose_name_plural': '2.2 · Modules'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-active', 'display_order'], 'verbose_name_plural': '4.3 · Templates'},
        ),
    ]
