# Generated by Django 3.0.7 on 2020-07-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0080_auto_20200630_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='shared',
        ),
    ]
