# Generated by Django 3.0.7 on 2020-07-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0082_shared_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shared',
            new_name='DefaultScripts',
        ),
    ]
