# Generated by Django 3.0.7 on 2020-07-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0083_auto_20200701_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedScripts',
            new_name='DefaultScriptTypes',
        ),
    ]
