# Generated by Django 3.0.7 on 2020-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0084_auto_20200701_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibraryScript',
            new_name='OptionalScript',
        ),
        migrations.AlterModelOptions(
            name='defaultscripts',
            options={'verbose_name': 'Default Scripts', 'verbose_name_plural': '3.2 · Default Scripts'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='library_script',
            new_name='optional_script',
        ),
        migrations.AlterField(
            model_name='defaultscripts',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='set name'),
        ),
    ]
