# Generated by Django 3.0.7 on 2020-07-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0085_auto_20200701_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='snippet_name',
            new_name='accessibility_name',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='snippet_text',
            new_name='accessibility_text',
        ),
    ]
