# Generated by Django 3.0.7 on 2020-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0086_auto_20200702_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear cache on next visit (or visit /c)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='clear cache on next visit (or visit /c)'),
        ),
    ]
