# Generated by Django 3.0.7 on 2020-07-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0087_auto_20200703_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalscript',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='default form instructions'),
        ),
    ]
