# Generated by Django 3.0.7 on 2020-07-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0088_auto_20200713_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'ordering': ['-active', 'family', 'style'], 'verbose_name': 'Font', 'verbose_name_plural': '3.1 · Fonts'},
        ),
    ]
