# Generated by Django 3.0.7 on 2020-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0089_auto_20200728_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='delete cache (or visit example.com/c)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cache_reset',
            field=models.BooleanField(default=False, verbose_name='delete cache (or visit example.com/c)'),
        ),
    ]
