# Generated by Django 3.0.7 on 2020-07-28 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0090_auto_20200728_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='accessibility_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='accessibility content'),
        ),
    ]
