# Generated by Django 3.0.7 on 2020-07-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0091_auto_20200728_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalscript',
            options={'ordering': ['-active', 'type', 'name', 'sort1', 'sort2'], 'verbose_name': 'Optional Scripts', 'verbose_name_plural': '3.3 · Optional Scripts'},
        ),
    ]
