# Generated by Django 3.0.7 on 2021-01-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0093_responsive_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='corner',
            field=models.CharField(choices=[('top left', 'top left'), ('top right', 'top right'), ('bottom left', 'bottom left'), ('bottom right', 'bottom right')], default='', max_length=255, verbose_name='reference corner'),
        ),
        migrations.AddField(
            model_name='module',
            name='css_id',
            field=models.CharField(default='', max_length=200, verbose_name='object ID'),
        ),
        migrations.AddField(
            model_name='module',
            name='horz_offset',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='horizontal offset (px)'),
        ),
        migrations.AddField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('absolute', 'absolute'), ('floating', 'floating'), ('relative', 'relative'), ('none', 'none')], default='', max_length=255, verbose_name='placement'),
        ),
        migrations.AddField(
            model_name='module',
            name='vert_offset',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='vertical offset (px)'),
        ),
    ]
