# Generated by Django 3.0.7 on 2021-01-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0094_auto_20210107_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='corner',
            field=models.CharField(choices=[('top left', 'top left'), ('top right', 'top right'), ('bottom left', 'bottom left'), ('bottom right', 'bottom right')], default='top left', max_length=255, verbose_name='reference corner'),
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('absolute', 'absolute'), ('floating', 'floating'), ('bottom', 'bottom')], default='absolute', max_length=255, verbose_name='placement'),
        ),
    ]
