# Generated by Django 3.0.7 on 2021-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0095_auto_20210107_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='horz_offset',
            field=models.SmallIntegerField(default=0, verbose_name='horizontal offset (px)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='vert_offset',
            field=models.SmallIntegerField(default=0, verbose_name='vertical offset (px)'),
        ),
    ]
