# Generated by Django 3.0.7 on 2021-01-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0096_auto_20210108_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('absolute', 'absolute'), ('floating', 'floating'), ('none', 'none')], default='absolute', max_length=255, verbose_name='placement'),
        ),
    ]
