# Generated by Django 3.0.7 on 2021-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0097_auto_20210108_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='bcc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='bcc: address'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='form instructions'),
        ),
        migrations.AlterField(
            model_name='language',
            name='mail_frm',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='address label in body'),
        ),
    ]
