# Generated by Django 3.0.7 on 2021-01-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0098_auto_20210111_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='corner',
            field=models.CharField(choices=[('top left', 'top left'), ('top right', 'top right'), ('bottom left', 'bottom left'), ('bottom right', 'bottom right')], default='top left', max_length=255, verbose_name='relative to'),
        ),
        migrations.AlterField(
            model_name='module',
            name='css_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='horz_offset',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='horizontal offset (px)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='vert_offset',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='vertical offset (px)'),
        ),
    ]
