# Generated by Django 3.0.7 on 2021-01-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0099_auto_20210112_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='horz_offset',
            field=models.FloatField(default=0, verbose_name='horizontal offset (px)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='vert_offset',
            field=models.FloatField(default=0, verbose_name='vertical offset (px)'),
        ),
    ]
