# Generated by Django 3.0.7 on 2021-06-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0100_auto_20210112_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefix',
            options={'ordering': ['display_order'], 'verbose_name': 'Combination', 'verbose_name_plural': '1.4 · Combinations'},
        ),
        migrations.AlterModelOptions(
            name='responsive',
            options={'ordering': ['display_order'], 'verbose_name': 'Screen', 'verbose_name_plural': '1.3 · Screens'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'URL & Settings', 'verbose_name_plural': '1.1 · URL & Settings'},
        ),
        migrations.AlterField(
            model_name='defaultscripts',
            name='responsive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Responsive', verbose_name='screen'),
        ),
        migrations.AlterField(
            model_name='font',
            name='source',
            field=models.CharField(blank=True, default='SOURCE NEEDED', max_length=100, verbose_name='WOFF filename'),
        ),
        migrations.AlterField(
            model_name='forwards',
            name='to_prefix',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='HTTP or HTTPS'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='active',
            field=models.BooleanField(default=False, verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='prefix',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Prefix', verbose_name='default combination'),
        ),
    ]
