# Generated by Django 3.0.7 on 2021-06-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0102_auto_20210622_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultscripts',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
    ]
