# Generated by Django 3.0.7 on 2021-07-03 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0105_auto_20210703_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='notes',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
