# Generated by Django 3.0.7 on 2021-07-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0106_module_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='form_business',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='business label'),
        ),
    ]
