# Generated by Django 3.0.7 on 2021-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0107_language_form_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='form_alert_fail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='send failed'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_alert_rcvd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='once sent (alert)'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_business',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_rcvd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='once sent'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_send',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='send button'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_sending',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='while sending'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='language',
            name='mail_frm',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='return address label'),
        ),
    ]
