# Generated by Django 3.0.7 on 2021-07-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0108_auto_20210703_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultscripts',
            options={'verbose_name': 'default scripts', 'verbose_name_plural': '3.2 · Default Scripts'},
        ),
        migrations.AlterModelOptions(
            name='font',
            options={'ordering': ['-active', 'family', 'style'], 'verbose_name': 'font', 'verbose_name_plural': '3.1 · Fonts'},
        ),
        migrations.AlterModelOptions(
            name='forwards',
            options={'verbose_name': 'redirect', 'verbose_name_plural': '4.2 · Redirects'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'note', 'verbose_name_plural': '4.4 · My Notes'},
        ),
        migrations.AlterModelOptions(
            name='optionalscript',
            options={'ordering': ['-active', 'type', 'name', 'sort1', 'sort2'], 'verbose_name': 'optional scripts', 'verbose_name_plural': '3.3 · Optional Scripts'},
        ),
        migrations.AlterModelOptions(
            name='prefix',
            options={'ordering': ['display_order'], 'verbose_name': 'combination', 'verbose_name_plural': '1.4 · Combination Codes'},
        ),
        migrations.AlterModelOptions(
            name='responsive',
            options={'ordering': ['display_order'], 'verbose_name': 'screen size', 'verbose_name_plural': '1.3 · Screen Sizes'},
        ),
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name': 'robots.txt', 'verbose_name_plural': '4.1· Robots.txt'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'website', 'verbose_name_plural': '1.1 · URL & Settings'},
        ),
        migrations.AlterField(
            model_name='prefix',
            name='responsive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.Responsive', verbose_name='screen size'),
        ),
        migrations.AlterField(
            model_name='responsive',
            name='source_dir',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='folder in /sync'),
        ),
        migrations.AlterField(
            model_name='responsive',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='pixel width in Illustrator'),
        ),
    ]
