# Generated by Django 3.0.7 on 2021-07-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0110_auto_20210726_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name': 'robots.txt', 'verbose_name_plural': '4.1 · Robots.txt'},
        ),
    ]
