# Generated by Django 3.0.7 on 2021-07-26 11:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0111_auto_20210726_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Instructions'),
        ),
    ]
