# Generated by Django 3.0.7 on 2021-07-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0112_auto_20210726_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodules',
            options={'ordering': ['zindex'], 'verbose_name': 'required by a page', 'verbose_name_plural': 'required by a page'},
        ),
        migrations.AlterModelOptions(
            name='prefixmodules',
            options={'ordering': ['zindex'], 'verbose_name': 'required by combination code', 'verbose_name_plural': 'required by combination code'},
        ),
        migrations.AlterField(
            model_name='pagemodules',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Module'),
        ),
        migrations.AlterField(
            model_name='pagemodules',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svija.Page'),
        ),
    ]
