# Generated by Django 3.0.7 on 2021-07-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0113_auto_20210726_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodules',
            options={'ordering': ['zindex'], 'verbose_name': 'The following module is required by a page', 'verbose_name_plural': 'The following modules are required by a page'},
        ),
        migrations.AlterModelOptions(
            name='prefixmodules',
            options={'ordering': ['zindex'], 'verbose_name': 'The following module is required by a combination code', 'verbose_name_plural': 'The following modules are required by a combination code'},
        ),
    ]
