# Generated by Django 3.2.7 on 2021-09-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0116_auto_20210907_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultscripts',
            options={'verbose_name': 'default scripts', 'verbose_name_plural': '3.1 · Default Scripts'},
        ),
        migrations.AlterModelOptions(
            name='font',
            options={'ordering': ['-active', 'family', 'style'], 'verbose_name': 'font', 'verbose_name_plural': '2.3 · Fonts'},
        ),
        migrations.AlterModelOptions(
            name='optionalscript',
            options={'ordering': ['-active', 'type', 'name', 'sort1', 'sort2'], 'verbose_name': 'optional scripts', 'verbose_name_plural': '3.2 · Optional Scripts'},
        ),
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['zindex'], 'verbose_name': 'Illustrator file', 'verbose_name_plural': 'Illustrator files'},
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Illustrator file (optional)'),
        ),
    ]
