# Generated by Django 3.2.7 on 2021-09-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0117_auto_20210913_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsive',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='upper limit ·\xa00=infinite'),
        ),
        migrations.AlterField(
            model_name='responsive',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='AI pixel width'),
        ),
    ]
