# Generated by Django 3.2.7 on 2021-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0118_auto_20210913_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsive',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='maximum pixel width'),
        ),
    ]
