# Generated by Django 3.2.7 on 2021-09-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0119_alter_responsive_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='svija.language'),
        ),
        migrations.AddField(
            model_name='page',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='svija.responsive', verbose_name='screen size'),
        ),
    ]
