# Generated by Django 3.2.7 on 2021-09-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0120_auto_20210914_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-visitable', 'url', 'language', 'screen', '-pub_date'], 'verbose_name_plural': '2.1 · Pages'},
        ),
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='svija.language', verbose_name='language'),
        ),
        migrations.AddField(
            model_name='module',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='svija.responsive', verbose_name='screen size'),
        ),
    ]
