# Generated by Django 3.2.7 on 2021-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0121_auto_20210914_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-active', 'sort1', 'name', 'screen'], 'verbose_name_plural': '2.2 · Modules'},
        ),
        migrations.AlterField(
            model_name='module',
            name='sort1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sort label'),
        ),
        migrations.AlterField(
            model_name='page',
            name='offsetx',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='offset x'),
        ),
        migrations.AlterField(
            model_name='page',
            name='offsety',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='offset y'),
        ),
        migrations.AlterField(
            model_name='page',
            name='override_dims',
            field=models.BooleanField(default=False, verbose_name='override default dimensions'),
        ),
        migrations.AlterField(
            model_name='page',
            name='visible',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='visible width'),
        ),
        migrations.AlterField(
            model_name='page',
            name='width',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Illustrator width'),
        ),
    ]
