# Generated by Django 3.2.7 on 2021-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0122_auto_20210914_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='optional',
            field=models.BooleanField(default=False, verbose_name='optional'),
        ),
        migrations.AlterField(
            model_name='language',
            name='default',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='default page'),
        ),
        migrations.AlterField(
            model_name='module',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Z-index'),
        ),
    ]
