# Generated by Django 3.2.7 on 2021-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0123_auto_20210914_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsive',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Illustrator pixel width'),
        ),
    ]
