# Generated by Django 3.2.7 on 2021-09-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0124_alter_responsive_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='css_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='object ID (optional)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='optional',
            field=models.BooleanField(default=False, verbose_name='always include'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sort1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sort label (optional)'),
        ),
    ]
