# Generated by Django 3.2.7 on 2021-09-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0125_auto_20210915_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='svija.language', verbose_name='default language'),
        ),
    ]
