# Generated by Django 3.2.7 on 2021-09-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0126_settings_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='prefix',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='svija.prefix', verbose_name='combination code'),
        ),
    ]
