# Generated by Django 3.2.7 on 2021-09-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0127_alter_page_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalscript',
            options={'ordering': ['-active', 'type', 'name', 'sort1', 'sort2'], 'verbose_name': 'optional script', 'verbose_name_plural': '3.2 · Optional Scripts'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sort category'),
        ),
        migrations.AlterField(
            model_name='optionalscript',
            name='sort1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sort category'),
        ),
    ]
