# Generated by Django 3.2.7 on 2021-10-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0129_alter_defaultscripts_responsive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultscripts',
            name='responsive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='svija.responsive', verbose_name='screen size'),
        ),
        migrations.AlterField(
            model_name='defaultscripttypes',
            name='scripts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.defaultscripts'),
        ),
    ]
