# Generated by Django 3.2.7 on 2021-10-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0130_auto_20211015_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultscripts',
            options={'verbose_name': 'script set', 'verbose_name_plural': '4.1 · Script Sets'},
        ),
        migrations.AlterModelOptions(
            name='defaultscripttypes',
            options={'ordering': ['order'], 'verbose_name': 'script'},
        ),
        migrations.AlterModelOptions(
            name='optionalscript',
            options={'ordering': ['-active', 'type', 'name', 'sort1', 'sort2'], 'verbose_name': 'DEPRECATED was optional script', 'verbose_name_plural': 'DEPRECATED · was Optional Scripts'},
        ),
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name': 'robots.txt', 'verbose_name_plural': '4.3 · Robots.txt'},
        ),
        migrations.AddField(
            model_name='page',
            name='default_scripts',
            field=models.ManyToManyField(blank=True, to='svija.DefaultScripts'),
        ),
    ]
