# Generated by Django 3.2.7 on 2021-10-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0131_auto_20211015_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultscripts',
            options={'verbose_name': 'scripts', 'verbose_name_plural': '4.1 · Scripts'},
        ),
        migrations.AlterModelOptions(
            name='defaultscripttypes',
            options={'ordering': ['order'], 'verbose_name': 'single script', 'verbose_name_plural': 'single scripts'},
        ),
        migrations.AlterField(
            model_name='defaultscripts',
            name='responsive',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='svija.responsive', verbose_name='screen size'),
        ),
    ]
