# Generated by Django 3.2.7 on 2021-10-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0132_auto_20211016_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultscripts',
            options={'verbose_name': 'scripts', 'verbose_name_plural': '3.1 · Scripts'},
        ),
        migrations.AlterModelOptions(
            name='forwards',
            options={'verbose_name': 'redirect', 'verbose_name_plural': '3.2 · Redirects'},
        ),
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name': 'robots.txt', 'verbose_name_plural': '3.3 · Robots.txt'},
        ),
    ]
