# Generated by Django 3.2.7 on 2021-10-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0133_auto_20211018_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodules',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.page'),
        ),
    ]
