# Generated by Django 3.2.7 on 2021-10-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0134_alter_pagemodules_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodules',
            options={'ordering': ['zindex'], 'verbose_name': 'reference to a module', 'verbose_name_plural': 'references to modules'},
        ),
        migrations.AlterModelOptions(
            name='pagescripts',
            options={'ordering': ['order'], 'verbose_name': 'reference to a script', 'verbose_name_plural': 'references to scripts'},
        ),
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['zindex'], 'verbose_name': 'reference to an Illustrator file', 'verbose_name_plural': 'references to Illustrator files'},
        ),
    ]
