# Generated by Django 3.2.7 on 2021-10-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0135_auto_20211018_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodules',
            options={'ordering': ['zindex'], 'verbose_name': 'link to a module', 'verbose_name_plural': 'links to modules'},
        ),
        migrations.AlterModelOptions(
            name='pagescripts',
            options={'ordering': ['order'], 'verbose_name': 'page-specific script', 'verbose_name_plural': 'page-specific scripts'},
        ),
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['zindex'], 'verbose_name': 'link to an Illustrator file', 'verbose_name_plural': 'links to Illustrator files'},
        ),
    ]
