# Generated by Django 3.2.7 on 2021-10-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0136_auto_20211018_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulescripts',
            options={'ordering': ['order'], 'verbose_name': 'included script', 'verbose_name_plural': 'included scripts'},
        ),
        migrations.AlterModelOptions(
            name='pagescripts',
            options={'ordering': ['order'], 'verbose_name': 'included script', 'verbose_name_plural': 'included scripts'},
        ),
    ]
