# Generated by Django 3.2.7 on 2021-10-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0137_auto_20211018_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodules',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.module'),
        ),
    ]
