# Generated by Django 3.2.7 on 2021-10-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0138_alter_pagemodules_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodules',
            options={'ordering': ['zindex'], 'verbose_name': 'link to module', 'verbose_name_plural': 'links to modules'},
        ),
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['zindex'], 'verbose_name': 'link to Illustrator file', 'verbose_name_plural': 'links to Illustrator files'},
        ),
    ]
