# Generated by Django 3.2.7 on 2021-10-20 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0139_auto_20211018_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svg',
            options={'ordering': ['zindex'], 'verbose_name': 'Illustrator file', 'verbose_name_plural': 'Illustrator files'},
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='code (visible in address bar)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='publication date'),
        ),
    ]
