# Generated by Django 3.2.7 on 2021-10-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0140_auto_20211020_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='code (visible to users)'),
        ),
    ]
