# Generated by Django 3.2.7 on 2021-10-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0141_alter_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='form_message',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='initial value'),
        ),
    ]
