# Generated by Django 3.2.7 on 2021-10-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0142_auto_20211020_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='svija.template'),
        ),
    ]
