# Generated by Django 3.2.7 on 2021-10-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0143_alter_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='bcc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='bcc address'),
        ),
    ]
