# Generated by Django 3.2.7 on 2021-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0144_alter_language_bcc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='site address'),
        ),
    ]
