# Generated by Django 3.2.7 on 2021-10-22 07:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0145_alter_settings_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultscripttypes',
            options={'ordering': ['order'], 'verbose_name': 'script', 'verbose_name_plural': 'scripts'},
        ),
        migrations.AddField(
            model_name='defaultscripts',
            name='insructions',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Instructions'),
        ),
    ]
