# Generated by Django 3.2.7 on 2021-10-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0146_auto_20211022_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultscripts',
            old_name='insructions',
            new_name='instructions',
        ),
    ]
