# Generated by Django 3.2.7 on 2021-10-22 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0147_rename_insructions_defaultscripts_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='svija.language'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='responsive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='svija.responsive', verbose_name='screen size'),
        ),
        migrations.AlterField(
            model_name='prefixmodules',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.module'),
        ),
        migrations.AlterField(
            model_name='prefixmodules',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.prefix'),
        ),
    ]
