# Generated by Django 3.2.7 on 2021-10-28 14:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0148_auto_20211022_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultscripts',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='defaultscripts',
            name='url',
            field=models.CharField(default='', max_length=60, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='defaultscripts',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
