# Generated by Django 3.2.7 on 2021-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0150_auto_20211028_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultscripts',
            name='url',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='link'),
        ),
    ]
