# Generated by Django 3.2.7 on 2021-11-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0152_auto_20211105_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('sort1', models.CharField(blank=True, default='', max_length=100, verbose_name='sort label (optional)')),
                ('load_order', models.PositiveSmallIntegerField(default=0, verbose_name='load order')),
                ('url', models.CharField(blank=True, default='', max_length=60, verbose_name='link')),
                ('instructions', models.TextField(blank=True, default='', max_length=2000, verbose_name='notes')),
            ],
            options={
                'verbose_name_plural': '3.1 · Scriptsx',
                'ordering': ['-active', 'sort1', 'name', 'load_order'],
            },
        ),
        migrations.CreateModel(
            name='ScriptScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CSS', 'CSS'), ('head JS', 'head JS'), ('body JS', 'body JS'), ('HTML', 'HTML'), ('form', 'form')], default='', max_length=255, verbose_name='type')),
                ('name', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='', max_length=50000, verbose_name='content')),
                ('order', models.IntegerField(default=0, verbose_name='load order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.script')),
            ],
            options={
                'verbose_name': 'included script',
                'verbose_name_plural': 'included scripts',
                'ordering': ['order'],
            },
        ),
    ]
