# Generated by Django 3.2.7 on 2021-11-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0153_script_scriptscripts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultscripts',
            options={'verbose_name': 'scripts', 'verbose_name_plural': '9.1 · Scripts'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-active', 'sort1', 'name', 'load_order'], 'verbose_name_plural': '3.1 · Scripts'},
        ),
        migrations.CreateModel(
            name='PageScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='load order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.page')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.script')),
            ],
            options={
                'verbose_name': 'link to script',
                'verbose_name_plural': 'links to script',
                'ordering': ['order'],
            },
        ),
    ]
