# Generated by Django 3.2.7 on 2021-11-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0154_auto_20211129_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultscripttypes',
            options={'ordering': ['order'], 'verbose_name': 'script deprecated', 'verbose_name_plural': 'scripts deprecated'},
        ),
        migrations.AddField(
            model_name='page',
            name='script',
            field=models.ManyToManyField(through='svija.PageScript', to='svija.Script'),
        ),
    ]
