# Generated by Django 3.2.7 on 2021-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0156_alter_script_load_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='form_alert_fail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='send failed (alert)'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_alert_rcvd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='email sent (alert)'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_rcvd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='email sent'),
        ),
        migrations.AlterField(
            model_name='language',
            name='form_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='initial status'),
        ),
    ]
