# Generated by Django 3.2.7 on 2021-11-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0157_auto_20211130_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-active', 'sort', 'name', 'load_order'], 'verbose_name_plural': '3.1 · Scripts'},
        ),
        migrations.RenameField(
            model_name='script',
            old_name='sort1',
            new_name='sort',
        ),
    ]
