# Generated by Django 3.2.7 on 2021-11-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0158_auto_20211130_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-active', 'sort', 'name'], 'verbose_name_plural': '3.1 · Scripts'},
        ),
        migrations.RemoveField(
            model_name='script',
            name='load_order',
        ),
    ]
