# Generated by Django 3.2.7 on 2022-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0159_auto_20211130_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='category',
            field=models.CharField(default='Main', max_length=200, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(default='Main', max_length=200, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='Main', max_length=200, verbose_name='category'),
        ),
    ]
