# Generated by Django 3.2.7 on 2022-02-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0160_auto_20220222_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='category',
        ),
    ]
