# Generated by Django 3.2.7 on 2022-02-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0161_remove_module_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='category',
            field=models.CharField(blank=True, default='Main', max_length=200, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sort1',
            field=models.CharField(blank=True, default='Main', max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, default='Main', max_length=200, verbose_name='category'),
        ),
    ]
