# Generated by Django 3.2.7 on 2022-02-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0162_auto_20220222_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'ordering': ['-active', 'category', 'family', 'style'], 'verbose_name': 'font', 'verbose_name_plural': '2.3 · Fonts'},
        ),
    ]
