# Generated by Django 3.2.7 on 2022-02-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0163_alter_font_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='source',
            field=models.CharField(blank=True, default='—', max_length=100, verbose_name='WOFF filename'),
        ),
    ]
