# Generated by Django 3.2.7 on 2022-02-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0164_alter_font_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
