# Generated by Django 3.2.7 on 2022-02-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0165_alter_font_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwards',
            name='to_prefix',
        ),
    ]
