# Generated by Django 3.2.7 on 2022-02-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0166_remove_forwards_to_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='language',
            name='no_email',
        ),
    ]
