# Generated by Django 3.2.7 on 2022-02-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0167_auto_20220227_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsive',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='responsive',
            name='meta_tag',
        ),
        migrations.RemoveField(
            model_name='responsive',
            name='source_dir',
        ),
    ]
