# Generated by Django 3.2.7 on 2022-02-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0168_auto_20220227_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsive',
            name='description',
        ),
    ]
