# Generated by Django 3.2.7 on 2022-02-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0170_auto_20220227_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='cache_reset',
        ),
        migrations.RemoveField(
            model_name='page',
            name='cache_reset',
        ),
    ]
