# Generated by Django 3.2.7 on 2022-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0171_auto_20220227_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-published', 'sort1', 'name', 'screen'], 'verbose_name_plural': '2.1 · Modules'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-visitable', 'url', 'language', 'screen', '-pub_date'], 'verbose_name_plural': '2.2 · Pages'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='sort2',
        ),
        migrations.AddField(
            model_name='page',
            name='eache_reset',
            field=models.BooleanField(default=False, verbose_name='delete cache (or visit example.com/c)'),
        ),
    ]
