# Generated by Django 3.2.7 on 2022-02-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0172_auto_20220227_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='notes',
        ),
    ]
