# Generated by Django 3.2.7 on 2022-02-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0173_remove_module_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultscripttypes',
            name='scripts',
        ),
        migrations.RemoveField(
            model_name='page',
            name='default_scripts',
        ),
        migrations.DeleteModel(
            name='DefaultScripts',
        ),
        migrations.DeleteModel(
            name='DefaultScriptTypes',
        ),
    ]
