# Generated by Django 3.2.7 on 2022-02-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0174_auto_20220227_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefixmodules',
            name='module',
        ),
        migrations.RemoveField(
            model_name='prefixmodules',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='page',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='prefix',
        ),
        migrations.DeleteModel(
            name='Prefix',
        ),
        migrations.DeleteModel(
            name='PrefixModules',
        ),
    ]
