# Generated by Django 3.2.7 on 2022-02-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0175_auto_20220227_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='cached',
        ),
    ]
