# Generated by Django 3.2.7 on 2022-02-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0176_remove_settings_cached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='secure',
        ),
    ]
