# Generated by Django 3.2.7 on 2022-02-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0178_remove_page_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template',
        ),
    ]
