# Generated by Django 3.2.7 on 2022-02-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0179_remove_page_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forwards',
            new_name='Redirect',
        ),
    ]
