# Generated by Django 3.2.7 on 2022-02-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0180_rename_forwards_redirect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Help',
        ),
    ]
