# Generated by Django 3.2.7 on 2022-02-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0181_delete_help'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
