# Generated by Django 3.2.7 on 2022-02-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0182_delete_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responsive',
            new_name='Screen',
        ),
    ]
