# Generated by Django 3.2.7 on 2022-02-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0183_rename_responsive_screen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
