# Generated by Django 3.2.7 on 2022-02-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0184_delete_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleScripts',
            new_name='ModuleScript',
        ),
    ]
