# Generated by Django 3.2.7 on 2022-02-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0185_rename_modulescripts_modulescript'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Svg',
            new_name='Illustrator',
        ),
        migrations.AlterModelOptions(
            name='pagescripts',
            options={'ordering': ['order'], 'verbose_name': 'included script 328', 'verbose_name_plural': 'included scripts 329'},
        ),
    ]
