# Generated by Django 3.2.7 on 2022-02-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0186_auto_20220227_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageScripts',
            new_name='AdditionalScript',
        ),
        migrations.AlterModelOptions(
            name='additionalscript',
            options={'ordering': ['order'], 'verbose_name': 'additional script', 'verbose_name_plural': 'additional scripts'},
        ),
    ]
