# Generated by Django 3.2.7 on 2022-02-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0187_auto_20220227_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageModules',
            new_name='PageModule',
        ),
    ]
