# Generated by Django 3.2.7 on 2022-03-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0188_rename_pagemodules_pagemodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='img_multiply',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='img_quality',
        ),
        migrations.AlterField(
            model_name='language',
            name='comment',
            field=models.TextField(default='Site built entirely in SVG with Svija – visit svija.love for more information!', max_length=5000, verbose_name='source code message'),
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('absolute', 'absolute'), ('floating', 'floating'), ('none', 'none')], default='absolute', max_length=255, verbose_name='position'),
        ),
    ]
