# Generated by Django 3.2.7 on 2022-03-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0189_auto_20220301_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirect',
            old_name='to_page',
            new_name='to_url',
        ),
    ]
