# Generated by Django 3.2.7 on 2022-03-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0191_rename_css_font_svg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='svg_name',
            new_name='svg_ref',
        ),
    ]
