# Generated by Django 3.2.7 on 2022-03-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0192_rename_svg_name_font_svg_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='source',
            new_name='woff',
        ),
    ]
