# Generated by Django 3.2.7 on 2022-03-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0193_rename_source_font_woff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='default',
            new_name='default_page',
        ),
    ]
