# Generated by Django 3.2.7 on 2022-03-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0194_rename_default_language_default_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order'], 'verbose_name_plural': '1.2 · Languages'},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='display_order',
            new_name='order',
        ),
    ]
