# Generated by Django 3.2.7 on 2022-03-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0195_auto_20220301_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['order'], 'verbose_name': 'screen size', 'verbose_name_plural': '1.3 · Screen Sizes'},
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='display_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='screen',
            old_name='limit',
            new_name='pixels',
        ),
    ]
