# Generated by Django 3.2.7 on 2022-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0196_auto_20220301_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-active', 'category', 'name'], 'verbose_name_plural': '3.1 · Scripts'},
        ),
        migrations.RemoveField(
            model_name='script',
            name='sort',
        ),
        migrations.AddField(
            model_name='script',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='category (optional)'),
        ),
    ]
