# Generated by Django 3.2.7 on 2022-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0197_auto_20220301_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-active', 'sort1', 'name', 'screen'], 'verbose_name_plural': '2.1 · Modules'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='published',
        ),
        migrations.AddField(
            model_name='module',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
