# Generated by Django 3.2.7 on 2022-03-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0198_auto_20220301_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='optional',
            new_name='always',
        ),
    ]
