# Generated by Django 3.2.7 on 2022-03-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0199_rename_optional_module_always'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-active', 'category', 'name', 'screen'], 'verbose_name_plural': '2.1 · Modules'},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='sort1',
            new_name='category',
        ),
    ]
