# Generated by Django 3.2.7 on 2022-03-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0201_auto_20220301_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-published', 'url', 'language', 'screen', '-pub_date'], 'verbose_name_plural': '2.2 · Pages'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='visitable',
            new_name='published',
        ),
    ]
