# Generated by Django 3.2.7 on 2022-03-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0202_auto_20220301_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='override_dims',
            new_name='override',
        ),
    ]
