# Generated by Django 3.2.7 on 2022-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0204_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='cached',
            field=models.BooleanField(default=False, verbose_name='cache active'),
        ),
    ]
