# Generated by Django 3.2.7 on 2022-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0205_alter_control_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='used',
            field=models.PositiveIntegerField(default=300, verbose_name='sync folder MB current'),
        ),
    ]
