# Generated by Django 3.2.7 on 2022-03-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0206_control_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='cached_h',
            field=models.BooleanField(default=False, verbose_name='cache active'),
        ),
        migrations.AddField(
            model_name='control',
            name='limit_h',
            field=models.PositiveIntegerField(default=300, verbose_name='sync folder MB max'),
        ),
        migrations.AddField(
            model_name='control',
            name='used_h',
            field=models.PositiveIntegerField(default=300, verbose_name='sync folder MB current'),
        ),
    ]
