# Generated by Django 3.2.7 on 2022-03-02 15:51

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0207_auto_20220302_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.ForeignKey(default=svija.models.get_sentinel_language_id, on_delete=models.SET(svija.models.get_sentinel_language), to='svija.language', verbose_name='default language'),
        ),
    ]
