# Generated by Django 3.2.7 on 2022-03-02 15:56

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0208_alter_settings_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='active',
            field=models.BooleanField(default=True, verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='robots',
            field=models.ForeignKey(default=svija.models.get_sentinel_robots_id, on_delete=models.SET(svija.models.get_sentinel_language), to='svija.robots', verbose_name='robots.txt'),
        ),
    ]
