# Generated by Django 3.2.7 on 2022-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0209_auto_20220302_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='accessibility_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='accessibility name'),
        ),
    ]
