# Generated by Django 3.2.7 on 2022-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0210_alter_page_accessibility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='woff',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='WOFF filename'),
        ),
    ]
