# Generated by Django 3.2.7 on 2022-05-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0211_alter_font_woff'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='always',
            field=models.BooleanField(default=False, verbose_name='always include'),
        ),
    ]
