# Generated by Django 3.2.7 on 2022-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0212_script_always'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='suppress_scripts',
            field=models.BooleanField(default=False, verbose_name='suppress default scripts'),
        ),
    ]
