# Generated by Django 3.2.7 on 2022-05-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0213_page_suppress_scripts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-active', 'category', 'name'], 'verbose_name_plural': '3.1 · Script Sets'},
        ),
    ]
