# Generated by Django 3.2.7 on 2022-05-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0214_alter_script_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='category',
            field=models.CharField(blank=True, default='Main', max_length=200, verbose_name='tag (optional)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(blank=True, default='Main', max_length=100, verbose_name='tag (optional)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, default='Main', max_length=200, verbose_name='tag (optional)'),
        ),
        migrations.AlterField(
            model_name='script',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='tag (optional)'),
        ),
    ]
