# Generated by Django 3.2.7 on 2022-06-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0215_auto_20220517_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Illustrator filename (opt.)'),
        ),
    ]
