# Generated by Django 3.2.7 on 2022-07-21 15:39

from django.db import migrations, models
import django.db.models.deletion
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0216_alter_module_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order'], 'verbose_name_plural': '1.2 · Sections'},
        ),
        migrations.AlterField(
            model_name='module',
            name='language',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='svija.language', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='svija.language', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.ForeignKey(default=svija.models.get_sentinel_language_id, on_delete=models.SET(svija.models.get_sentinel_language), to='svija.language', verbose_name='default section'),
        ),
    ]
