# Generated by Django 3.2.7 on 2022-07-22 07:44

from django.db import migrations, models
import django.db.models.deletion
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0217_auto_20220721_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.ForeignKey(default=svija.models.get_default_section, on_delete=django.db.models.deletion.PROTECT, to='svija.language', verbose_name='section'),
        ),
    ]
