# Generated by Django 3.2.7 on 2022-07-22 07:48

from django.db import migrations, models
import django.db.models.deletion
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0218_alter_page_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='language',
            field=models.ForeignKey(default=svija.models.get_default_section, on_delete=django.db.models.deletion.PROTECT, to='svija.language', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.ForeignKey(default=svija.models.get_default_section, on_delete=models.SET(svija.models.get_sentinel_language), to='svija.language', verbose_name='default section'),
        ),
    ]
