# Generated by Django 3.2.7 on 2022-07-22 12:44

from django.db import migrations, models
import django.db.models.deletion
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0219_auto_20220722_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustrator',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrator_fk', to='svija.page'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='robots',
            field=models.ForeignKey(default=svija.models.get_sentinel_robots_id, on_delete=models.SET(svija.models.get_sentinel_robots_id), to='svija.robots', verbose_name='robots.txt'),
        ),
    ]
