# Generated by Django 3.2.7 on 2022-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0220_auto_20220722_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['width'], 'verbose_name': 'screen size', 'verbose_name_plural': '1.3 · Screen Sizes'},
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Illustrator file'),
        ),
        migrations.AlterField(
            model_name='page',
            name='suppress_modules',
            field=models.BooleanField(default=False, verbose_name='suppress modules'),
        ),
        migrations.AlterField(
            model_name='page',
            name='suppress_scripts',
            field=models.BooleanField(default=False, verbose_name='suppress scripts'),
        ),
    ]
