# Generated by Django 3.2.7 on 2022-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0221_auto_20220722_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='override',
        ),
        migrations.AddField(
            model_name='page',
            name='default_dims',
            field=models.BooleanField(default=True, verbose_name='use default dimensions'),
        ),
        migrations.AlterField(
            model_name='page',
            name='suppress_modules',
            field=models.BooleanField(default=True, verbose_name='include modules'),
        ),
        migrations.AlterField(
            model_name='page',
            name='suppress_scripts',
            field=models.BooleanField(default=True, verbose_name='include scripts'),
        ),
    ]
