# Generated by Django 3.2.7 on 2022-07-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0222_auto_20220722_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='suppress_modules',
            new_name='incl_modules',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='suppress_scripts',
            new_name='incl_scripts',
        ),
    ]
