# Generated by Django 3.2.7 on 2022-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0223_auto_20220722_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='incl_modules',
            field=models.BooleanField(default=True, verbose_name='default modules'),
        ),
        migrations.AlterField(
            model_name='page',
            name='incl_scripts',
            field=models.BooleanField(default=True, verbose_name='default scripts'),
        ),
    ]
