# Generated by Django 3.2.7 on 2022-07-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0224_auto_20220722_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='default_dims',
            field=models.BooleanField(default=True, verbose_name='default dimensions'),
        ),
    ]
