# Generated by Django 3.2.7 on 2022-07-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0225_alter_page_default_dims'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Section',
        ),
    ]
