# Generated by Django 3.2.7 on 2022-07-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0226_rename_language_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='language',
            new_name='section',
        ),
    ]
