# Generated by Django 3.2.7 on 2022-07-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0227_rename_language_module_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='language',
            new_name='section',
        ),
    ]
