# Generated by Django 3.2.7 on 2022-07-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0228_rename_language_settings_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-published', 'url', 'section', 'screen', '-pub_date'], 'verbose_name_plural': '2.2 · Pages'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='language',
            new_name='section',
        ),
    ]
