# Generated by Django 3.2.7 on 2022-07-22 15:15

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0229_auto_20220722_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robots',
            options={'ordering': ['name'], 'verbose_name': 'robots.txt', 'verbose_name_plural': '3.3 · Robots.txt'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='robots',
            field=models.ForeignKey(default=svija.models.get_default_robots, on_delete=svija.models.get_default_robots, to='svija.robots', verbose_name='robots.txt'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='section',
            field=models.ForeignKey(default=svija.models.get_default_section, on_delete=svija.models.get_default_section, to='svija.section', verbose_name='default section'),
        ),
    ]
