# Generated by Django 3.2.7 on 2022-07-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0230_auto_20220722_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='accessibility_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='link name'),
        ),
    ]
