# Generated by Django 3.2.7 on 2022-08-30 10:31

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0231_alter_page_accessibility_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='robots',
            field=models.ForeignKey(default=svija.models.get_default_robots_id, on_delete=models.SET(svija.models.get_default_robots), to='svija.robots', verbose_name='robots.txt'),
        ),
    ]
