# Generated by Django 3.2.7 on 2022-08-30 10:35

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0232_alter_settings_robots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='section',
            field=models.ForeignKey(default=svija.models.get_sentinel_section_id, on_delete=models.SET(svija.models.get_sentinel_section), to='svija.section', verbose_name='default section'),
        ),
    ]
