# Generated by Django 3.2.7 on 2022-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0233_alter_settings_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='default_page',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='default page address'),
        ),
    ]
