# Generated by Django 3.2.7 on 2022-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0234_alter_section_default_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mail_port',
            field=models.IntegerField(blank=True, default=0, verbose_name='email server port'),
        ),
    ]
