# Generated by Django 3.2.7 on 2022-09-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0235_alter_settings_mail_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='script',
            name='url',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='link'),
        ),
    ]
