# Generated by Django 3.2.7 on 2022-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0237_alter_screen_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='code',
            field=models.CharField(default='', max_length=2, verbose_name='two-letter code'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='pixels',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='maximum pixel width'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='width',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Artboard pixel width'),
        ),
    ]
