# Generated by Django 3.2.7 on 2022-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0238_auto_20221202_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('attached', 'attached'), ('floating', 'floating'), ('none', 'none')], default='attached', max_length=255, verbose_name='position'),
        ),
    ]
