# Generated by Django 3.2.7 on 2022-12-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0239_alter_module_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'ordering': ['-enabled', 'category', 'family', 'style'], 'verbose_name': 'font', 'verbose_name_plural': '2.3 · Fonts'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-enabled', 'category', 'order', 'name', 'screen'], 'verbose_name_plural': '2.1 · Modules'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-enabled', 'category', 'name'], 'verbose_name_plural': '3.1 · Script Sets'},
        ),
        migrations.RenameField(
            model_name='additionalscript',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='font',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='illustrator',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='modulescript',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='pagemodule',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='pagescript',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='redirect',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='script',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='scriptscripts',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='active',
            new_name='enabled',
        ),
    ]
