# Generated by Django 3.2.7 on 2022-12-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0241_auto_20221202_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='offsetx',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='offset x'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='offsety',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='offset y'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='visible',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='visible width'),
        ),
    ]
