# Generated by Django 3.2.7 on 2022-12-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0242_auto_20221202_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='mail_port',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='email server port'),
        ),
    ]
