# Generated by Django 4.1.4 on 2022-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0243_alter_settings_mail_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='adobe',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Adobe CSS'),
        ),
    ]
