# Generated by Django 4.1.4 on 2022-12-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0244_font_adobe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='font',
            name='adobe',
        ),
    ]
