# Generated by Django 4.1.4 on 2022-12-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0246_font_adobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='adobe_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Adobe src URL'),
        ),
    ]
