# Generated by Django 4.1.4 on 2022-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0247_font_adobe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='adobe_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Adobe WOFF URL'),
        ),
    ]
