# Generated by Django 4.1.4 on 2023-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0249_alter_font_adobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='adobe',
            field=models.TextField(blank=True, default='', max_length=99000, verbose_name='Adobe CSS'),
        ),
    ]
