# Generated by Django 4.1.4 on 2023-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0250_alter_font_adobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='adobe_link',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Pasted Adobe link'),
        ),
        migrations.AlterField(
            model_name='font',
            name='adobe_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Adobe Font URL'),
        ),
    ]
