# Generated by Django 4.1.4 on 2023-04-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0251_font_adobe_link_alter_font_adobe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='adobe',
            field=models.TextField(blank=True, default='', max_length=99000, verbose_name='link contents'),
        ),
        migrations.AlterField(
            model_name='font',
            name='adobe_link',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='pasted Adobe link'),
        ),
        migrations.AlterField(
            model_name='font',
            name='adobe_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='font file URL'),
        ),
    ]
