# Generated by Django 4.1.4 on 2023-04-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0252_alter_font_adobe_alter_font_adobe_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='tag (optional)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='tag (optional)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='tag (optional)'),
        ),
    ]
