# Generated by Django 4.1.4 on 2023-04-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0253_alter_font_category_alter_module_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-enabled', 'name', 'section', 'screen', 'order'], 'verbose_name_plural': '2.1 · Modules'},
        ),
    ]
