# Generated by Django 4.1.4 on 2023-04-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0254_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-enabled', 'name', 'section', 'screen'], 'verbose_name_plural': '2.1 · Modules'},
        ),
    ]
