# Generated by Django 4.1.4 on 2023-04-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0255_alter_module_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptscripts',
            name='content',
            field=models.TextField(default='', max_length=200000, verbose_name='content'),
        ),
    ]
