# Generated by Django 4.2.1 on 2023-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0256_alter_scriptscripts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='pixels',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='break point'),
        ),
    ]
