# Generated by Django 4.2.1 on 2023-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0257_alter_screen_pixels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='code',
            field=models.CharField(default='', max_length=2, verbose_name='artboard code'),
        ),
    ]
