# Generated by Django 4.2.1 on 2023-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0259_alter_section_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='Illustrator artboard code'),
        ),
    ]
