# Generated by Django 4.2.1 on 2023-06-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0261_alter_section_default_page_alter_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='google',
            field=models.BooleanField(default=False, verbose_name='Google font'),
        ),
    ]
