# Generated by Django 4.2.1 on 2023-06-29 15:23

from django.db import migrations
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0262_alter_font_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=svija.models.UrlField(default='', max_length=200, verbose_name='address'),
        ),
    ]
