# Generated by Django 4.2.1 on 2023-06-30 09:16

from django.db import migrations
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0263_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=svija.models.alphaLower(default='', max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=svija.models.alphaLower(default='', max_length=20, verbose_name='code (visible to users)'),
        ),
    ]
