# Generated by Django 4.2.1 on 2023-06-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0264_alter_page_url_alter_section_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagescript',
            options={'ordering': ['script'], 'verbose_name': 'link to script', 'verbose_name_plural': 'links to script'},
        ),
        migrations.RemoveField(
            model_name='pagescript',
            name='order',
        ),
    ]
