# Generated by Django 4.2.1 on 2023-06-30 15:35

from django.db import migrations
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0265_alter_pagescript_options_remove_pagescript_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=svija.models.addAiToEnd(blank=True, default='', max_length=200, verbose_name='Illustrator file'),
        ),
    ]
