# Generated by Django 4.2.1 on 2023-07-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0267_alter_illustrator_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='artboard name'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='description'),
        ),
    ]
