# Generated by Django 4.2.1 on 2023-07-01 19:21

from django.db import migrations
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0268_alter_screen_code_alter_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='code',
            field=svija.models.alphaLower(default='', max_length=20, verbose_name='artboard name'),
        ),
    ]
