# Generated by Django 4.2.1 on 2023-07-03 07:30

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0269_alter_screen_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='code',
            field=svija.models.alphaLower(default='', max_length=20, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='robots',
            field=models.ForeignKey(blank=True, default=svija.models.get_default_robots_id, on_delete=models.SET(svija.models.get_default_robots), to='svija.robots', verbose_name='robots.txt'),
        ),
    ]
