# Generated by Django 4.2.1 on 2023-07-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0270_alter_section_code_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='default_page',
            field=models.CharField(default='', max_length=200, verbose_name='default page'),
        ),
        migrations.AlterField(
            model_name='section',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='destination email'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='section title'),
        ),
    ]
