# Generated by Django 4.2.1 on 2023-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0271_alter_section_default_page_alter_section_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='style',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='style'),
        ),
    ]
