# Generated by Django 4.2.1 on 2023-07-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0272_alter_font_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'ordering': ['-enabled', 'category', 'family', 'style', 'svg_ref'], 'verbose_name': 'font', 'verbose_name_plural': '2.3 · Fonts'},
        ),
    ]
