# Generated by Django 4.2.1 on 2023-07-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0273_alter_font_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='adobe_link',
            new_name='adobe_pasted',
        ),
        migrations.RenameField(
            model_name='font',
            old_name='adobe',
            new_name='adobe_sheet',
        ),
    ]
