# Generated by Django 4.2.1 on 2023-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0274_rename_adobe_link_font_adobe_pasted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='weight'),
        ),
    ]
