# Generated by Django 4.2.1 on 2023-07-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0275_font_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['order', 'width'], 'verbose_name': 'screen size', 'verbose_name_plural': '1.3 · Screen Sizes'},
        ),
    ]
