# Generated by Django 4.2.1 on 2023-07-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0276_alter_screen_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='category',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='order',
            new_name='zindex',
        ),
    ]
