# Generated by Django 4.2.1 on 2023-07-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0278_alter_screen_offsetx_alter_screen_offsety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mail_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='email username'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mail_pass',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='email password'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mail_srv',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='email server'),
        ),
    ]
