# Generated by Django 4.2.1 on 2023-07-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0279_settings_notes_alter_settings_mail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='corner',
            field=models.CharField(choices=[('top left', 'top left'), ('top right', 'top right'), ('bottom left', 'bottom left'), ('bottom right', 'bottom right')], default='top left', max_length=255, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('attached', 'attached'), ('floating', 'floating'), ('none', 'none')], default='attached', max_length=255, verbose_name='floating/attached'),
        ),
    ]
