# Generated by Django 4.2.1 on 2023-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0280_alter_module_corner_alter_module_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='offsetx',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='x offset'),
        ),
        migrations.AlterField(
            model_name='page',
            name='offsety',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='y offset'),
        ),
    ]
