# Generated by Django 4.2.1 on 2023-07-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0281_alter_page_offsetx_alter_page_offsety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagescript',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.script', verbose_name='script set'),
        ),
    ]
