# Generated by Django 4.2.1 on 2024-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0283_alter_screen_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Illustrator file'),
        ),
    ]
