# Generated by Django 4.2.1 on 2024-06-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0285_alter_illustrator_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['order', 'width'], 'verbose_name': 'screen size', 'verbose_name_plural': '1.2 · Screen Sizes'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name_plural': '1.3 · Sections'},
        ),
    ]
