# Generated by Django 4.2.1 on 2024-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0286_alter_screen_options_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-enabled', 'name', 'section', 'screen'], 'verbose_name_plural': '2.1 · Components'},
        ),
        migrations.AlterModelOptions(
            name='pagemodule',
            options={'ordering': ['zindex'], 'verbose_name': 'link to component', 'verbose_name_plural': 'links to components'},
        ),
        migrations.AlterField(
            model_name='control',
            name='limit',
            field=models.PositiveIntegerField(default=300, verbose_name='SYNC folder MB max'),
        ),
        migrations.AlterField(
            model_name='control',
            name='limit_h',
            field=models.PositiveIntegerField(default=300, verbose_name='SYNC folder MB max'),
        ),
        migrations.AlterField(
            model_name='control',
            name='used',
            field=models.PositiveIntegerField(default=300, verbose_name='SYNC folder MB current'),
        ),
        migrations.AlterField(
            model_name='control',
            name='used_h',
            field=models.PositiveIntegerField(default=300, verbose_name='SYNC folder MB current'),
        ),
        migrations.AlterField(
            model_name='page',
            name='incl_modules',
            field=models.BooleanField(default=True, verbose_name='default components'),
        ),
    ]
