# Generated by Django 4.2.1 on 2024-06-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0287_alter_module_options_alter_pagemodule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-enabled', 'name', 'section', 'screen'], 'verbose_name': 'component', 'verbose_name_plural': '2.2 · Components'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-published', 'url', 'section', 'screen', '-pub_date'], 'verbose_name_plural': '2.1 · Pages'},
        ),
        migrations.AlterModelOptions(
            name='robots',
            options={'ordering': ['name'], 'verbose_name': 'robots file', 'verbose_name_plural': '3.3 · Robots.txt'},
        ),
    ]
