# Generated by Django 4.2.1 on 2025-04-04 07:20

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0288_alter_module_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-enabled', 'name', 'section', 'screen'], 'verbose_name': 'module', 'verbose_name_plural': '2.2 · Modules'},
        ),
        migrations.AlterModelOptions(
            name='pagemodule',
            options={'ordering': ['zindex'], 'verbose_name': 'link to module', 'verbose_name_plural': 'links to modules'},
        ),
        migrations.AddField(
            model_name='section',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AddField(
            model_name='section',
            name='language',
            field=models.BooleanField(default=True, verbose_name='is a language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='incl_modules',
            field=models.BooleanField(default=True, verbose_name='default modules'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='code',
            field=svija.models.alphaStar(default='', max_length=20, verbose_name='artboard name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=svija.models.alphaStar(default='', max_length=20, verbose_name='address'),
        ),
    ]
