# Generated by Django 4.2.1 on 2025-04-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0289_alter_module_options_alter_pagemodule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='language',
            field=models.BooleanField(default=False, verbose_name='is a language'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
    ]
