# Generated by Django 4.2.1 on 2025-04-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0290_alter_section_language_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='language',
            field=models.BooleanField(default=False, verbose_name='language code'),
        ),
    ]
