# Generated by Django 4.2.1 on 2025-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0291_alter_section_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustrator',
            name='zindex',
            field=models.SmallIntegerField(default=0, verbose_name='z index'),
        ),
        migrations.AlterField(
            model_name='module',
            name='zindex',
            field=models.SmallIntegerField(default=0, verbose_name='Z-index'),
        ),
        migrations.AlterField(
            model_name='pagemodule',
            name='zindex',
            field=models.SmallIntegerField(default=0, verbose_name='z index'),
        ),
    ]
