# Generated by Django 4.2.1 on 2025-04-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0292_alter_illustrator_zindex_alter_module_zindex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'website setting', 'verbose_name_plural': 'website settings'},
        ),
    ]
