# Generated by Django 4.2.1 on 2025-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0293_alter_settings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'website', 'verbose_name_plural': 'website settings'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='on line'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='maps_api_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Maps API key'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tracking_on',
            field=models.BooleanField(default=False, verbose_name='cookies allowed'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='site url'),
        ),
    ]
