# Generated by Django 4.2.1 on 2025-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0294_alter_settings_options_alter_settings_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'verbose_name': 'url redirect', 'verbose_name_plural': 'url redirects'},
        ),
        migrations.AlterField(
            model_name='redirect',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='redirect enabled'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='from_url',
            field=models.CharField(default='', max_length=200, verbose_name='from URL'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='to_url',
            field=models.CharField(default='', max_length=200, verbose_name='to URL'),
        ),
    ]
