# Generated by Django 4.2.1 on 2025-04-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0295_alter_redirect_options_alter_redirect_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='adobe_pasted',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='adobe link'),
        ),
        migrations.AlterField(
            model_name='font',
            name='adobe_sheet',
            field=models.TextField(blank=True, default='', max_length=99000, verbose_name='adobe contents'),
        ),
        migrations.AlterField(
            model_name='font',
            name='adobe_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='adobe url'),
        ),
        migrations.AlterField(
            model_name='font',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='optional tag'),
        ),
        migrations.AlterField(
            model_name='font',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='font enabled'),
        ),
        migrations.AlterField(
            model_name='font',
            name='family',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='font family'),
        ),
        migrations.AlterField(
            model_name='font',
            name='google',
            field=models.BooleanField(default=False, verbose_name='google font'),
        ),
        migrations.AlterField(
            model_name='font',
            name='style',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='font style'),
        ),
        migrations.AlterField(
            model_name='font',
            name='svg_ref',
            field=models.CharField(default='', max_length=100, verbose_name='svg name'),
        ),
        migrations.AlterField(
            model_name='font',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='font weight'),
        ),
        migrations.AlterField(
            model_name='font',
            name='woff',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='woff name'),
        ),
    ]
