# Generated by Django 4.2.1 on 2025-04-08 09:13

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0296_alter_font_adobe_pasted_alter_font_adobe_sheet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=svija.models.alphaStar(default='', max_length=20, verbose_name='section address'),
        ),
        migrations.AlterField(
            model_name='section',
            name='comment',
            field=models.TextField(default='Site built entirely in Adobe Illustrator – visit svija.com for more information!', max_length=5000, verbose_name='source code message'),
        ),
        migrations.AlterField(
            model_name='section',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='section enabled'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form_alert_fail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='send failed alert'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form_alert_rcvd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='email sent alert'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='section name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='touch',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='iphone icon'),
        ),
    ]
