# Generated by Django 4.2.1 on 2025-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0297_alter_section_options_alter_section_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='form_business',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='business label'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form_email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='email label'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form_message',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='message label'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name label'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form_rcvd',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sent status'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form_send',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='send label'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form_sending',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='sending status'),
        ),
    ]
