# Generated by Django 4.2.1 on 2025-04-08 09:39

from django.db import migrations, models
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0298_alter_section_form_business_alter_section_form_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['order', 'width'], 'verbose_name': 'screen size', 'verbose_name_plural': 'screen sizes'},
        ),
        migrations.AlterField(
            model_name='screen',
            name='code',
            field=svija.models.alphaStar(default='', max_length=20, verbose_name='artboard code'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='screen name'),
        ),
    ]
