# Generated by Django 4.2.1 on 2025-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0299_alter_screen_options_alter_screen_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-enabled', 'category', 'name'], 'verbose_name': 'script set', 'verbose_name_plural': 'script sets'},
        ),
        migrations.AlterField(
            model_name='script',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='optional tag'),
        ),
        migrations.AlterField(
            model_name='script',
            name='instructions',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='instructions notes'),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='script name'),
        ),
        migrations.AlterField(
            model_name='script',
            name='url',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='instructions link'),
        ),
    ]
