# Generated by Django 4.2.1 on 2025-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0300_alter_script_options_alter_script_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='script set name'),
        ),
        migrations.AlterField(
            model_name='scriptscripts',
            name='content',
            field=models.TextField(default='', max_length=200000, verbose_name='script content'),
        ),
        migrations.AlterField(
            model_name='scriptscripts',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='script name'),
        ),
        migrations.AlterField(
            model_name='scriptscripts',
            name='type',
            field=models.CharField(choices=[('CSS', 'CSS'), ('head JS', 'head JS'), ('body JS', 'body JS'), ('HTML', 'HTML'), ('form', 'form')], default='', max_length=255, verbose_name='script type'),
        ),
    ]
