# Generated by Django 4.2.1 on 2025-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0301_alter_script_name_alter_scriptscripts_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-enabled', 'name', 'section', 'screen'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterField(
            model_name='module',
            name='corner',
            field=models.CharField(choices=[('top left', 'top left'), ('top right', 'top right'), ('bottom left', 'bottom left'), ('bottom right', 'bottom right')], default='top left', max_length=255, verbose_name='corner position'),
        ),
        migrations.AlterField(
            model_name='module',
            name='css_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='css id'),
        ),
        migrations.AlterField(
            model_name='module',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='illustrator file'),
        ),
        migrations.AlterField(
            model_name='module',
            name='instructions',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='instructions notes'),
        ),
        migrations.AlterField(
            model_name='module',
            name='offsetx',
            field=models.FloatField(default=0, verbose_name='horizontal offset'),
        ),
        migrations.AlterField(
            model_name='module',
            name='offsety',
            field=models.FloatField(default=0, verbose_name='vertical offset'),
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('attached', 'attached'), ('floating', 'floating'), ('none', 'none')], default='attached', max_length=255, verbose_name='floating attached'),
        ),
        migrations.AlterField(
            model_name='module',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='optional tag'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='instructions link'),
        ),
        migrations.AlterField(
            model_name='module',
            name='zindex',
            field=models.SmallIntegerField(default=0, verbose_name='z index'),
        ),
    ]
