# Generated by Django 4.2.1 on 2025-04-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0302_alter_module_options_alter_module_corner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modulescript',
            name='content',
            field=models.TextField(default='', max_length=50000, verbose_name='script content'),
        ),
        migrations.AlterField(
            model_name='modulescript',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='script name'),
        ),
        migrations.AlterField(
            model_name='modulescript',
            name='type',
            field=models.CharField(choices=[('CSS', 'CSS'), ('head JS', 'head JS'), ('body JS', 'body JS'), ('HTML', 'HTML'), ('form', 'form')], default='', max_length=255, verbose_name='script type'),
        ),
    ]
