# Generated by Django 4.2.1 on 2025-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0303_alter_module_name_alter_modulescript_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robots',
            options={'ordering': ['name'], 'verbose_name': 'robots file', 'verbose_name_plural': 'robots.txt'},
        ),
        migrations.AlterField(
            model_name='robots',
            name='contents',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='robots',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
    ]
