# Generated by Django 4.2.1 on 2025-04-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0304_alter_robots_options_alter_robots_contents_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-published', 'url', 'section', 'screen', '-pub_date'], 'verbose_name_plural': 'page listing'},
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='optional tag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='page title'),
        ),
    ]
