# Generated by Django 4.2.1 on 2025-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0305_alter_page_options_alter_page_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illustrator',
            options={'ordering': ['zindex'], 'verbose_name': 'illustrator file', 'verbose_name_plural': 'illustrator files'},
        ),
        migrations.AlterField(
            model_name='additionalscript',
            name='content',
            field=models.TextField(default='', max_length=50000, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='additionalscript',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='additionalscript',
            name='type',
            field=models.CharField(choices=[('CSS', 'CSS'), ('head JS', 'head JS'), ('body JS', 'body JS'), ('HTML', 'HTML'), ('form', 'form')], default='', max_length=255, verbose_name='script type'),
        ),
    ]
