# Generated by Django 4.2.1 on 2025-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0306_alter_illustrator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustrator',
            name='filename',
            field=models.CharField(default='', max_length=200, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='analytics_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='analytics id'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mail_tls',
            field=models.BooleanField(default=True, verbose_name='use tls'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='maps_api_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='maps api key'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='p3_color',
            field=models.BooleanField(default=True, verbose_name='display p3'),
        ),
    ]
