# Generated by Django 4.2.1 on 2025-04-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0307_alter_illustrator_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalscript',
            name='type',
            field=models.CharField(choices=[('CSS', 'css script'), ('head JS', 'head js script'), ('body JS', 'body js script'), ('HTML', 'html script'), ('form', 'form script')], default='', max_length=255, verbose_name='script type'),
        ),
        migrations.AlterField(
            model_name='modulescript',
            name='type',
            field=models.CharField(choices=[('CSS', 'css script'), ('head JS', 'head js script'), ('body JS', 'body js script'), ('HTML', 'html script'), ('form', 'form script')], default='', max_length=255, verbose_name='script type'),
        ),
        migrations.AlterField(
            model_name='scriptscripts',
            name='type',
            field=models.CharField(choices=[('CSS', 'css script'), ('head JS', 'head js script'), ('body JS', 'body js script'), ('HTML', 'html script'), ('form', 'form script')], default='', max_length=255, verbose_name='script type'),
        ),
    ]
