# Generated by Django 4.2.1 on 2025-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0308_alter_additionalscript_type_alter_modulescript_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('attached', 'position attached'), ('floating', 'position floating'), ('none', 'position none')], default='attached', max_length=255, verbose_name='floating attached'),
        ),
    ]
