# Generated by Django 4.2.1 on 2025-04-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0309_alter_module_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'ordering': ['-enabled', 'category', 'family', 'style', 'svg_ref'], 'verbose_name': 'font', 'verbose_name_plural': 'font model list'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-enabled', 'name', 'section', 'screen'], 'verbose_name': 'module', 'verbose_name_plural': 'module model list'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-published', 'url', 'section', 'screen', '-pub_date'], 'verbose_name_plural': 'page model list'},
        ),
        migrations.AlterModelOptions(
            name='redirect',
            options={'verbose_name': 'url redirect', 'verbose_name_plural': 'url redirects model list'},
        ),
        migrations.AlterModelOptions(
            name='robots',
            options={'ordering': ['name'], 'verbose_name': 'robots file', 'verbose_name_plural': 'robots model list'},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['order', 'width'], 'verbose_name': 'screen size', 'verbose_name_plural': 'screen size model list'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-enabled', 'category', 'name'], 'verbose_name': 'script set', 'verbose_name_plural': 'script set model list'},
        ),
        migrations.AlterModelOptions(
            name='scriptscripts',
            options={'ordering': ['order'], 'verbose_name': 'included script', 'verbose_name_plural': 'included script'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'section', 'verbose_name_plural': 'section model list'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'website', 'verbose_name_plural': 'website settings model list'},
        ),
    ]
