# Generated by Django 4.2.1 on 2025-04-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0310_alter_font_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='pixels',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='max width'),
        ),
    ]
