# Generated by Django 4.2.1 on 2025-04-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0311_alter_screen_pixels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalscript',
            options={'ordering': ['order'], 'verbose_name': 'script', 'verbose_name_plural': 'scripts'},
        ),
        migrations.AlterModelOptions(
            name='robots',
            options={'ordering': ['name'], 'verbose_name': 'robots.txt file', 'verbose_name_plural': 'robots model list'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-enabled', 'category', 'name'], 'verbose_name': 'script library', 'verbose_name_plural': 'script library model list'},
        ),
        migrations.AlterField(
            model_name='module',
            name='offsetx',
            field=models.FloatField(default=0, verbose_name='x offset'),
        ),
        migrations.AlterField(
            model_name='module',
            name='offsety',
            field=models.FloatField(default=0, verbose_name='y offset'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='pagescript',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svija.script', verbose_name='script library'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='script library name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='title'),
        ),
    ]
