# Generated by Django 4.2.1 on 2025-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0313_alter_font_category_alter_module_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='pixels',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='break point'),
        ),
    ]
