# Generated by Django 4.2.1 on 2025-04-11 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0314_alter_screen_pixels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='instructions notes'),
        ),
    ]
