# Generated by Django 4.2.1 on 2025-04-11 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0315_alter_script_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='instructions notes'),
        ),
    ]
