# Generated by Django 4.2.1 on 2025-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0316_alter_module_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='colorAccent',
            field=models.CharField(blank=True, default='rgb(87%, 100%, 60% )', max_length=80, verbose_name='accent color'),
        ),
        migrations.AddField(
            model_name='settings',
            name='colorDark',
            field=models.CharField(blank=True, default='rgb(15%, 15%, 15% )', max_length=80, verbose_name='dark color'),
        ),
        migrations.AddField(
            model_name='settings',
            name='colorMain',
            field=models.CharField(blank=True, default='rgb(70%, 100%, 0%)', max_length=80, verbose_name='main color'),
        ),
    ]
