# Generated by Django 4.2.1 on 2025-05-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0317_settings_coloraccent_settings_colordark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='colorAccent',
            new_name='color_accent',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='colorDark',
            new_name='color_dark',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='colorMain',
            new_name='color_main',
        ),
    ]
