# Generated by Django 4.2.1 on 2025-05-13 13:19

from django.db import migrations
import svija.models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0318_rename_coloraccent_settings_color_accent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='from_url',
            field=svija.models.slashOrHTTPS(default='', max_length=200, verbose_name='from URL'),
        ),
    ]
