# Generated by Django 4.2.1 on 2025-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0319_alter_redirect_from_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='maps_api_key',
        ),
        migrations.AddField(
            model_name='settings',
            name='adobe_project',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='adobe project ID'),
        ),
    ]
