# Generated by Django 4.2.1 on 2025-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0320_remove_settings_maps_api_key_settings_adobe_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='adobe_project',
            field=models.CharField(blank=True, default='', max_length=66, verbose_name='adobe project ID'),
        ),
    ]
