# Generated by Django 4.2.1 on 2025-06-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0321_alter_settings_adobe_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='adobe',
            field=models.BooleanField(default=False, verbose_name='adobe font'),
        ),
    ]
