# Generated by Django 4.2.1 on 2025-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0322_font_adobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='adobe',
            field=models.BooleanField(default=True, verbose_name='adobe font'),
        ),
    ]
