# Generated by Django 4.2.1 on 2025-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0323_alter_font_adobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='adobe_project',
            field=models.CharField(blank=True, default='', max_length=66, verbose_name='adobe web project ID'),
        ),
    ]
