# Generated by Django 4.2.1 on 2025-06-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0324_alter_settings_adobe_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='adobe_sheet',
            field=models.TextField(blank=True, default='', max_length=99000, verbose_name='adobe contents'),
        ),
    ]
