# Generated by Django 4.2.1 on 2025-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0325_settings_adobe_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='font',
            name='adobe_sheet',
        ),
        migrations.AlterField(
            model_name='settings',
            name='adobe_project',
            field=models.CharField(blank=True, default='', max_length=66, verbose_name='project ID'),
        ),
    ]
