# Generated by Django 4.2.1 on 2025-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0326_remove_font_adobe_sheet_alter_settings_adobe_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='adobe',
            field=models.BooleanField(default=False, verbose_name='adobe font'),
        ),
    ]
