# Generated by Django 4.2.1 on 2025-06-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0327_alter_font_adobe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='font',
            name='adobe_pasted',
        ),
        migrations.AlterField(
            model_name='settings',
            name='adobe_project',
            field=models.CharField(blank=True, default='', max_length=66, verbose_name='adobe project id'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='adobe_sheet',
            field=models.TextField(blank=True, default='', max_length=99000, verbose_name='adobe stylesheet'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='analytics_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='google analytics id'),
        ),
    ]
