# Generated by Django 5.2.5 on 2025-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0329_alter_font_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='mail_srv',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='email server'),
        ),
    ]
