# Generated by Django 5.2.5 on 2025-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svija', '0330_control_mail_srv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='mail_srv',
            field=models.CharField(blank=True, default='svija.site', max_length=200, verbose_name='email server'),
        ),
    ]
